# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Calculator.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(404, 302)
        self.gridLayoutWidget = QtWidgets.QWidget(Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 150, 271, 141))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.angka3 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.angka3.setObjectName("angka3")
        self.gridLayout.addWidget(self.angka3, 0, 2, 1, 1)
        self.angka1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.angka1.setObjectName("angka1")
        self.gridLayout.addWidget(self.angka1, 0, 0, 1, 1)
        self.angka2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.angka2.setObjectName("angka2")
        self.gridLayout.addWidget(self.angka2, 0, 1, 1, 1)
        self.dell = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.dell.setObjectName("dell")
        self.gridLayout.addWidget(self.dell, 0, 3, 1, 1)
        self.angka0 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.angka0.setObjectName("angka0")
        self.gridLayout.addWidget(self.angka0, 1, 3, 1, 1)
        self.angka9 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.angka9.setObjectName("angka9")
        self.gridLayout.addWidget(self.angka9, 2, 2, 1, 1)
        self.angka8 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.angka8.setObjectName("angka8")
        self.gridLayout.addWidget(self.angka8, 2, 1, 1, 1)
        self.angka7 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.angka7.setObjectName("angka7")
        self.gridLayout.addWidget(self.angka7, 2, 0, 1, 1)
        self.angka6 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.angka6.setObjectName("angka6")
        self.gridLayout.addWidget(self.angka6, 1, 2, 1, 1)
        self.angka5 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.angka5.setObjectName("angka5")
        self.gridLayout.addWidget(self.angka5, 1, 1, 1, 1)
        self.angka4 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.angka4.setObjectName("angka4")
        self.gridLayout.addWidget(self.angka4, 1, 0, 1, 1)
        self.angka_titik = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.angka_titik.setObjectName("angka_titik")
        self.gridLayout.addWidget(self.angka_titik, 2, 3, 1, 1)
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(290, 150, 101, 141))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.operator_tambah = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.operator_tambah.setObjectName("operator_tambah")
        self.verticalLayout.addWidget(self.operator_tambah)
        self.operator_kurang = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.operator_kurang.setObjectName("operator_kurang")
        self.verticalLayout.addWidget(self.operator_kurang)
        self.operato_kali = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.operato_kali.setObjectName("operato_kali")
        self.verticalLayout.addWidget(self.operato_kali)
        self.operato_bagi = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.operato_bagi.setObjectName("operato_bagi")
        self.verticalLayout.addWidget(self.operato_bagi)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 110, 381, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.clear = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.clear.setObjectName("clear")
        self.horizontalLayout.addWidget(self.clear)
        self.enter = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.enter.setObjectName("enter")
        self.horizontalLayout.addWidget(self.enter)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(100, 10, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(10, 39, 381, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit.setFont(font)
        self.lineEdit.setText("")
        self.lineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.signals()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.angka3.setText(_translate("Dialog", "3"))
        self.angka1.setText(_translate("Dialog", "1"))
        self.angka2.setText(_translate("Dialog", "2"))
        self.dell.setText(_translate("Dialog", "Dell"))
        self.angka0.setText(_translate("Dialog", "0"))
        self.angka9.setText(_translate("Dialog", "9"))
        self.angka8.setText(_translate("Dialog", "8"))
        self.angka7.setText(_translate("Dialog", "7"))
        self.angka6.setText(_translate("Dialog", "6"))
        self.angka5.setText(_translate("Dialog", "5"))
        self.angka4.setText(_translate("Dialog", "4"))
        self.angka_titik.setText(_translate("Dialog", "."))
        self.operator_tambah.setText(_translate("Dialog", "+"))
        self.operator_kurang.setText(_translate("Dialog", "-"))
        self.operato_kali.setText(_translate("Dialog", "X"))
        self.operato_bagi.setText(_translate("Dialog", ":"))
        self.clear.setText(_translate("Dialog", "Clear"))
        self.enter.setText(_translate("Dialog", "Enter"))
        self.label.setText(_translate("Dialog", "CALCULATOR STANDARD V2.0"))

    def signals(self):
        self.enter.clicked.connect(self.calc)
        self.clear.clicked.connect(self.rest)
        self.operator_tambah.clicked.connect(self.action_plus)
        self.operator_kurang.clicked.connect(self.action_minus)
        self.operato_kali.clicked.connect(self.action_mul)
        self.operato_bagi.clicked.connect(self.action_div)
        self.dell.clicked.connect(self.action_del)
        self.angka0.clicked.connect(self.action0)
        self.angka1.clicked.connect(self.action1)
        self.angka2.clicked.connect(self.action2)
        self.angka3.clicked.connect(self.action3)
        self.angka4.clicked.connect(self.action4)
        self.angka5.clicked.connect(self.action5)
        self.angka6.clicked.connect(self.action6)
        self.angka7.clicked.connect(self.action7)
        self.angka8.clicked.connect(self.action8)
        self.angka9.clicked.connect(self.action9)
        self.angka_titik.clicked.connect(self.action_titik)

    def rest(self):
        self.lineEdit.setText('')

    def calc(self):
        data = self.lineEdit.text()
        try:
            if "x" in data:
                data = data.replace("x", "*")
            if ":" in data:
                data = data.replace(":", "/")
            if "^" in data:
                data = data.replace("^", "**")
            hasil = eval(data)
            self.lineEdit.setText(str(hasil))
        except:
            self.lineEdit.setText('kesalahan pada input!')
    
    def action_plus(self):
        text = self.lineEdit.text()
        self.lineEdit.setText(text + "+")

    def action_minus(self):
        text = self.lineEdit.text()
        self.lineEdit.setText(text + "-")
 
    def action_div(self):
        text = self.lineEdit.text()
        self.lineEdit.setText(text + ":")
 
    def action_mul(self):
        text = self.lineEdit.text()
        self.lineEdit.setText(text + "x")
 
    def action_point(self):
        text = self.lineEdit.text()
        self.lineEdit.setText(text + ".")
 
    def action0(self):
        text = self.lineEdit.text()
        self.lineEdit.setText(text + "0")
 
    def action1(self):
        text = self.lineEdit.text()
        self.lineEdit.setText(text + "1")
 
    def action2(self):
        text = self.lineEdit.text()
        self.lineEdit.setText(text + "2")
 
    def action3(self):
        text = self.lineEdit.text()
        self.lineEdit.setText(text + "3")
 
    def action4(self):
        text = self.lineEdit.text()
        self.lineEdit.setText(text + "4")
 
    def action5(self):
        text = self.lineEdit.text()
        self.lineEdit.setText(text + "5")
 
    def action6(self):
        text = self.lineEdit.text()
        self.lineEdit.setText(text + "6")
 
    def action7(self):
        text = self.lineEdit.text()
        self.lineEdit.setText(text + "7")
 
    def action8(self):
        text = self.lineEdit.text()
        self.lineEdit.setText(text + "8")
 
    def action9(self):
        text = self.lineEdit.text()
        self.lineEdit.setText(text + "9")
 
    def action_titik(self):
        text = self.lineEdit.text()
        self.lineEdit.setText(text + ".")
 
    def action_del(self):
        text = self.lineEdit.text()
        print(text[:len(text)-1])
        self.lineEdit.setText(text[:len(text)-1])


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
